name: Publish WAGon Docs
run-name: Compiling and publishing WAGon docs
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: linux_amd64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: echo "The ${{ gitea.repository }} repository has been cloned to the runner."

      - name: Compile docs
        run: RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --all --no-deps

      - name: Publish docs
        run: cp -r target/doc/* /var/www/wagon
